import { Roboto } from 'next/font/google';
import "./globals.css";
import MainHeader from "@/components/shared/MainHeader";
import MainFooter from "@/components/shared/MainFooter";
import ScrollToTop from '@/components/client/ScrollToTop';
import SmoothScroll from '@/components/shared/SmoothScroll';
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'], 
  variable: '--font-roboto',
});

export const metadata = {
  title: "Shiv Kumar Sharma",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${roboto.variable}`}>
      <body
        className= {`bg-white dark:bg-background-dark font-sans text-[#1c160d] dark:text-white  antialiased`}
      >
          <SmoothScroll />
               <MainHeader/>
               <main> 
               {children}
                </main>
               <MainFooter />
                <ScrollToTop />
              
      </body>
    </html>
  );
}
